'use client';
import Image from 'next/image';
import {useEffect,useState} from 'react';
import {api} from '../../lib/api';
type Obj=Record<string,any>;
function Data({value}:{value:unknown}){return <pre>{JSON.stringify(value,null,2)}</pre>}
export default function Supervisor(){
 const [sessions,setSessions]=useState<Obj[]>([]),[selected,setSelected]=useState(''),[data,setData]=useState<Obj|null>(null),[eventId,setEventId]=useState(''),[error,setError]=useState('');
 useEffect(()=>{setSelected(new URLSearchParams(location.search).get('session')||'');},[]);
 useEffect(()=>{let live=true;const refresh=async()=>{try{const all=await api('/api/supervisor/sessions');if(!live)return;setSessions(all);const id=selected||all[0]?.conversation_id;if(id){const next=await api('/api/supervisor/session/'+id);if(live)setData(next);}setError('');}catch(e){if(live)setError(String(e));}};refresh();const timer=setInterval(refresh,2500);return()=>{live=false;clearInterval(timer)};},[selected]);
 const turns=data?.events?.filter((e:Obj)=>e.proposal)||[],e=turns.find((x:Obj)=>x.event_id===eventId)||turns[0],p=e?.proposal,d=e?.decision,s=e?.state_after||data?.state,b=p?.boundary_checks?.[0];
 const audio=data?.events?.find((x:Obj)=>x.type==='tts'&&x.turn_id===e?.turn_id),timings={...e?.latency,...audio?.latency};
 return <div className="supervisor"><header><a className="brand" href="/"><Image className="brandmark" src="/halyk-logo.png" alt="" width={42} height={42} priority /> Halyk <b>CallAI</b></a><span className="eyebrow">SUPERVISOR · LIVE EVIDENCE</span><a href="/">← Клиентский экран</a></header><div className="super-heading"><div><span className="eyebrow">ОТ ЗАПРОСА К ПРОВЕРЯЕМОМУ РЕШЕНИЮ</span><h1>Почему выбран этот маршрут?</h1></div><span className="voice-badge"><span className="live-dot"/> Обновление каждые 2,5 с</span></div><div className="super-select"><select aria-label="Разговор" value={selected||data?.state?.conversation_id||''} onChange={x=>{setSelected(x.target.value);setEventId('')}}>{sessions.map(x=><option key={x.conversation_id} value={x.conversation_id}>{x.history?.[0]?.text?.slice(0,70)||'Новый разговор'} · {x.conversation_id.slice(0,8)}</option>)}</select><select aria-label="Ход" value={e?.event_id||''} onChange={x=>setEventId(x.target.value)}>{turns.map((x:Obj)=><option key={x.event_id} value={x.event_id}>Ход {x.state_after.turn_number}: {x.user_text.slice(0,60)}</option>)}</select></div>{error&&<div className="error">{error}</div>}
 {!e?<div className="panel empty">Начните разговор на клиентском экране. Здесь появятся реальные решения и источники.</div>:<><section className="why panel"><span className="eyebrow">WHY THIS ROUTE?</span><div className="route-grid"><div><small>ВЫБРАНО</small><strong>{d.scenarios.join(' + ')||p.system_intent}</strong><span className="pill">{d.action}</span></div><div><small>БЛИЖАЙШАЯ АЛЬТЕРНАТИВА</small><strong>{b?.neighbor_id||p.alternatives.join(', ')||'—'}</strong></div><div><small>ГРАНИЦА</small><strong className={b?.status==='missing'?'amber':''}>{b?.status?.toUpperCase()||'NO BOUNDARY'}</strong></div></div><div className="fact"><small>РАЗЛИЧАЮЩИЙ ФАКТ</small><p>{b?.distinguishing_fact||p.reason}</p></div><div className="evidence-grid">{p.evidence.map((x:Obj)=><blockquote key={x.evidence_id}><span className="evidence-type">{x.polarity} {x.supersedes?'· supersedes '+x.supersedes:''}</span><p>«{x.quote||x.fact}»</p><small>{x.source_type} / {x.source_id} · {x.evidence_id}</small></blockquote>)}</div>{p.boundary_checks.length>1&&<details><summary>Все границы ({p.boundary_checks.length})</summary><Data value={p.boundary_checks}/></details>}</section>
 <div className="super-columns"><section className="panel"><h2>Разговор</h2><div className="mini-transcript">{s.history.map((m:Obj)=><div className={m.role} key={m.turn_id}><small>{m.role==='user'?'Клиент':'CallAI'}</small><p>{m.text}</p></div>)}</div></section><section className="panel"><h2>Состояние <span className="pill">v{s.state_version}</span></h2><dl><dt>Активная тема</dt><dd>{s.active_scenario||'—'}</dd><dt>Стек тем</dt><dd>{s.topic_stack.join(' → ')||'Пусто'}</dd><dt>Язык</dt><dd>{s.language} → {s.response_language}</dd><dt>LLM-вызовы роутера / retry</dt><dd>{e.llm_calls} / {e.retry_count}</dd></dl><p className="subtle">Response LLM calls: {e.composition_llm_calls||0}</p><h3>Слоты и исправления</h3><Data value={s.slots_by_topic}/><h3>Ожидаемое подтверждение</h3><Data value={s.pending_action}/></section><section className="panel"><h2>Исполнение и время</h2><div className="timeline">{Object.entries(timings).map(([name,v])=><div key={name}><span>{name.replaceAll('_',' ')}</span><b>{v===null?'—':(Number(v)/1000).toFixed(3)+' s'}</b><i style={{width:Math.min(100,Number(v)/Math.max(1,e.latency.total_text_ms)*100)+'%'}}/></div>)}</div><h3>Mock backend</h3><Data value={e.backend_actions}/><h3>KB / источники</h3><Data value={{lookups:e.kb_lookups,citations:e.citations}}/><h3>Ошибки</h3><Data value={e.errors}/></section></div><details className="panel"><summary>Полный trace · состояния до/после · запросы · voice events</summary><Data value={{turn:e,voice:data?.events?.filter((x:Obj)=>!x.proposal)}}/></details></>}
 <p className="disclosure">Локальное демо · содержит тестовые персональные данные starter kit · операции выполняются в mock backend.</p></div>
}
