'use client';
import {useEffect,useRef,useState} from 'react';
import {api,demos,Message,Session} from '../lib/api';
import {PlaybackGate} from '../lib/playback.mjs';
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[language,setLanguage]=useState<'ru'|'kk'>('ru'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[voice,setVoice]=useState(false),[recording,setRecording]=useState(false),[speaking,setSpeaking]=useState(false),[demo,setDemo]=useState(-1),[step,setStep]=useState(0),[latency,setLatency]=useState<number|null>(null);
 const recorder=useRef<MediaRecorder|null>(null),gate=useRef(new PlaybackGate()),end=useRef<HTMLDivElement>(null),busyRef=useRef(false),latestTurn=useRef('');
 const kk=language==='kk';
 useEffect(()=>{api('/api/voice/status').then(x=>setVoice(x.configured)).catch(()=>setVoice(false));const id=localStorage.getItem('callai-session');if(id)api('/api/session/'+id).then(s=>{setSession(s);setMessages(s.history);setLanguage(s.response_language)}).catch(()=>localStorage.removeItem('callai-session'));return()=>{gate.current.interrupt();recorder.current?.stream.getTracks().forEach(t=>t.stop());}},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
 function stopAudio(){gate.current.interrupt();setSpeaking(false);if(session&&latestTurn.current)api('/api/voice/interruption',{conversation_id:session.conversation_id,turn_id:latestTurn.current}).catch(()=>{});}
 async function speak(conversationId:string,turn:string,token:number,responseReadyAt:number){
  try{
   const response=await fetch('/api/voice/speech?stream=true',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:conversationId,turn_id:turn}),signal:gate.current.signal(token)});
   if(!response.ok)throw new Error(kk?'Дауыстық жауап қолжетімсіз; жауап мәтіні сақталды.':'Озвучивание недоступно; текст ответа сохранён.');
   await gate.current.playResponse(response,token,(metrics:Record<string,number|boolean|null>)=>{
    api('/api/voice/playback',{conversation_id:conversationId,turn_id:turn,...metrics}).catch(()=>{});
   },{responseReadyAt,onPlaying:()=>setSpeaking(true),onEnded:()=>setSpeaking(false)});
  }catch(e){if(gate.current.current(token)){setSpeaking(false);setError(String(e));}}
 }
 async function fresh(){stopAudio();setError('');try{const s=await api('/api/session',{language});setSession(s);setMessages([]);setLatency(null);setDemo(-1);setStep(0);localStorage.setItem('callai-session',s.conversation_id);return s;}catch(e){setError(String(e));return null;}}
 async function send(value=text,confirm?:string,mode='text',stt?:number,supplied?:Session){
  if(!value.trim()||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');stopAudio();const token=gate.current.generation;
  try{let s=supplied||session;if(!s){s=await api('/api/session',{language});setSession(s);localStorage.setItem('callai-session',s!.conversation_id);}if(!s)return;
   const turn=crypto.randomUUID();latestTurn.current=turn;setMessages(m=>[...m,{role:'user',text:value,turn_id:turn}]);setText('');
   const r=await api('/api/chat',{conversation_id:s.conversation_id,turn_id:turn,text:value,language,expected_state_version:s.state_version,confirm_operation_id:confirm||null,input_mode:mode,stt_latency_ms:stt??null});
   const responseReadyAt=performance.now();
   setMessages(m=>[...m,{role:'assistant',text:r.text,turn_id:turn+':assistant'}]);setSession({...s,state_version:r.state_version,pending_action:r.pending_action});setLanguage(r.language);setLatency(r.latency.total_text_ms);
   // The committed text turn is ready: TTS must not hold the input/barge-in lock.
   if(mode==='voice'&&gate.current.current(token))void speak(s.conversation_id,turn,token,responseReadyAt);
  }catch(e){setError(String(e));if(session)api('/api/session/'+session.conversation_id).then(setSession).catch(()=>{});}finally{busyRef.current=false;setBusy(false);}
 }
 async function mic(){
  stopAudio();if(recording){recorder.current?.stop();setRecording(false);return;}if(busyRef.current)return;
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);setBusy(true);try{const response=await fetch('/api/voice/transcribe?language='+language,{method:'POST',headers:{'Content-Type':rec.mimeType},body:new Blob(chunks,{type:rec.mimeType})});const result=await response.json();if(!response.ok)throw new Error(result.detail);setBusy(false);await send(result.text,undefined,'voice',result.latency_ms);}catch(e){setError(String(e));setBusy(false);}};rec.start();setRecording(true);setError('');}catch{setError(kk?'Микрофонға рұқсат беріңіз немесе мәтін жазыңыз.':'Разрешите доступ к микрофону или напишите сообщение.');}
 }
 async function startDemo(i:number){const s=await fresh();if(!s)return;setDemo(i);setStep(1);await send(demos[i].steps[0],undefined,'text',undefined,s);}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brandmark">h</span><span>Halyk <b>CallAI</b></span></a><span className="eyebrow">INSURANCE ASSISTANT</span><h1>{kk?'Сақтандыру. Түсінікті тілде.':'Страхование. На вашем языке.'}</h1><p className="subtle">{kk?'Сұрағыңызды айтыңыз. Қажетті деректерді тексеріп, келесі қадамға көмектесеміз.':'Расскажите, что случилось. Проверим данные и поможем сделать следующий шаг.'}</p><button className="new" onClick={fresh} disabled={busy||recording}>＋ {kk?'Жаңа әңгіме':'Новый разговор'}</button><div className="demo-title">ПОПРОБУЙТЕ В ДЕМО</div><nav className="demos">{demos.map((d,i)=><button key={d.name} className={demo===i?'selected':''} disabled={busy||recording} onClick={()=>startDemo(i)}><b>{d.name}</b><small>{d.detail}</small><span>↗</span></button>)}</nav><a className="supervisor-link" href={'/supervisor'+(session?'?session='+session.conversation_id:'')}>Пульт супервизора <span>↗</span></a><div className="disclosure">HackAlem · Демонстрационный продукт<br/>Данные и операции Saqta Insurance из starter kit.</div></aside>
 <main className="customer"><header><div><span className="live-dot"/> {busy?(kk?'Жауап дайындауда':'Готовим ответ'):(kk?'Көмектесуге дайын':'Готов помочь')}<small> AI-ассистент</small></div><div className="header-actions"><span className={'voice-badge '+(!voice?'muted':'')}>{voice?'◉ Голос настроен':'○ Голос недоступен'}</span><div className="language">{(['ru','kk'] as const).map(l=><button key={l} className={language===l?'active':''} onClick={()=>setLanguage(l)} disabled={busy}>{l.toUpperCase()}</button>)}</div></div></header>
 <section className="conversation" aria-live="polite">{messages.length===0?<div className="welcome"><div className="assistant-orb">✳</div><span className="eyebrow">ВАШ ПОМОЩНИК ПО СТРАХОВАНИЮ</span><h2>{kk?'Қалай көмектесе аламын?':'Чем могу помочь?'}</h2><p>{kk?'Полис, төлем немесе сақтандыру оқиғасы туралы сұраңыз.':'Полис, оплата, страховой случай — начнём с вашего вопроса.'}</p><div className="welcome-chips">{['Где ближайший офис?','Нужна помощь с полисом','Сақтандыру туралы сұрағым бар'].map(t=><button key={t} onClick={()=>setText(t)}>{t} ↗</button>)}</div></div>:messages.map(m=><article key={m.turn_id} className={'message '+m.role}>{m.role==='assistant'&&<div className="avatar">✳</div>}<div><small>{m.role==='assistant'?'Halyk CallAI':(kk?'Сіз':'Вы')}</small><p>{m.text}</p></div></article>)}{busy&&<div className="thinking"><span/> Проверяем запрос и данные…</div>}<div ref={end}/></section>
 <footer>{session?.pending_action&&!busy&&<div className="confirm"><span>{kk?'Әрекет сіздің растауыңызды күтеді.':'Действие ожидает вашего подтверждения.'}</span><button onClick={()=>send(kk?'Растаймын':'Подтверждаю',session.pending_action!.operation_id)}>{kk?'Растау':'Подтвердить'}</button></div>}{demo>=0&&step<demos[demo].steps.length&&!busy&&<button className="next-demo" onClick={()=>{send(demos[demo].steps[step]);setStep(step+1)}}>Следующая реплика демо →</button>}{error&&<div className="error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();send()}} className="composer"><button type="button" className={'mic '+(recording?'recording':'')} onClick={mic} disabled={!voice||(busy&&!speaking)} title={recording?'Завершить запись':'Начать запись'} aria-label={recording?'Завершить запись':'Микрофон'}>{recording?'■':'♩'}</button><input aria-label="Сообщение" placeholder={recording?'Слушаю… нажмите ■, чтобы отправить':(kk?'Сұрағыңызды жазыңыз…':'Напишите ваш вопрос…')} value={text} onChange={e=>setText(e.target.value)} disabled={busy||recording}/><button className="send" disabled={busy||recording||!text.trim()} aria-label="Отправить">↑</button></form><div className="footer-note"><span>{recording?'● Запись · отправляется только после остановки':speaking?'Воспроизводится AI-голос · микрофон прервёт ответ':'Ответы опираются на данные Saqta Insurance · AI-голос'}</span>{latency!==null&&<span>{(latency/1000).toFixed(1)} с</span>}</div></footer></main></div>
}
